import './globals.css'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Cubox",
    template: "%s | Cubox",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900 text-7xl">
        <header className="bg-gradient-to-r from-blue-500 to-indigo-600 text-white py-4 shadow-md">
          <div className="max-w-7xl mx-auto px-6 lg:px-8 flex justify-between items-center">
            <h1 className="text-2xl font-bold">Next.js</h1>
          </div>
        </header>

        <main className="max-w-7xl mx-auto px-6 lg:px-8 py-8">
          {children}
        </main>

        <footer className="bg-gray-900 text-gray-300 py-6 mt-8">
          <div className="max-w-7xl mx-auto px-6 lg:px-8 text-center">
            <p className="text-lg font-semibold">© {new Date().getFullYear()} Next.js</p>
            <p className="text-sm mt-1">Built with ❤️ by `tahsin` using Next.js</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
